### ISSUE TITLE
add option `ignoreRule` to support ignore some specific selector

### ISSUE THREAD

**Issue by lovetingyuan** [kristerkari/css-to-react-native-transform#199]
```css
.foo {
  color: red;
}
.bar {
  font-size: 12px;
}
```

```js
css2rn(csscode, {
  ignoreRule(selector) {
    if (selector === '.foo') { return true }
  }
})
```

result:
```js
{
  "bar": { fontSize: 12 }
}
```
