### ISSUE TITLE
Add experimental support for CSS media queries

### ISSUE THREAD

**Issue by kristerkari** [kristerkari/css-to-react-native-transform#7]
```css
.container {
  background-color: #f00;
}

@media (orientation: landscape) {
  .container {
    background-color: #00f;
  }
}
```

↓ ↓ ↓ ↓ ↓ ↓

```js
{
  container: {
    backgroundColor: "#f00",
  },
  "@media (orientation: landscape)": {
    container: {
      backgroundColor: "#00f",
    },
  },
}
```
